stages:
- stage: stage_0
  jobs:
  - job: ros-melodic-catkin
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-catkin
- stage: stage_1
  jobs:
  - job: ros-melodic-genmsg
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-genmsg
- stage: stage_2
  jobs:
  - job: ros-melodic-gencpp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-gencpp
  - job: ros-melodic-geneus
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-geneus
  - job: ros-melodic-genlisp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-genlisp
  - job: ros-melodic-gennodejs
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-gennodejs
  - job: ros-melodic-genpy
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-genpy
- stage: stage_3
  jobs:
  - job: ros-melodic-message-generation
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-message-generation
  - job: ros-melodic-cpp-common
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-cpp-common
- stage: stage_4
  jobs:
  - job: ros-melodic-rostime
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rostime
- stage: stage_5
  jobs:
  - job: ros-melodic-roscpp-traits
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roscpp-traits
- stage: stage_6
  jobs:
  - job: ros-melodic-roscpp-serialization
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roscpp-serialization
- stage: stage_7
  jobs:
  - job: ros-melodic-message-runtime
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-message-runtime
- stage: stage_8
  jobs:
  - job: ros-melodic-rosbuild
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosbuild
  - job: ros-melodic-rosmake
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosmake
  - job: ros-melodic-cmake-modules
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-cmake-modules
  - job: ros-melodic-ros-environment
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-ros-environment
- stage: stage_9
  jobs:
  - job: ros-melodic-rospack
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rospack
- stage: stage_10
  jobs:
  - job: ros-melodic-roslib
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roslib
- stage: stage_11
  jobs:
  - job: ros-melodic-rosunit
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosunit
- stage: stage_12
  jobs:
  - job: ros-melodic-rosconsole
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosconsole
  - job: ros-melodic-std-msgs
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-std-msgs
- stage: stage_13
  jobs:
  - job: ros-melodic-rosgraph-msgs
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosgraph-msgs
  - job: ros-melodic-roslang
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roslang
  - job: ros-melodic-xmlrpcpp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-xmlrpcpp
- stage: stage_14
  jobs:
  - job: ros-melodic-roscpp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roscpp
trigger:
- experimental
pr: none
