pool:
  vmImage: ubuntu-16.04
trigger:
- experimental
pr: none
stages:
- stage: stage_0
  jobs:
  - job: ros_melodic_catkin
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-catkin
- stage: stage_1
  jobs:
  - job: ros_melodic_genmsg
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-genmsg
- stage: stage_2
  jobs:
  - job: ros_melodic_gencpp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-gencpp
  - job: ros_melodic_geneus
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-geneus
  - job: ros_melodic_genlisp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-genlisp
  - job: ros_melodic_gennodejs
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-gennodejs
  - job: ros_melodic_genpy
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-genpy
- stage: stage_3
  jobs:
  - job: ros_melodic_message_generation
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-message-generation
  - job: ros_melodic_cpp_common
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-cpp-common
- stage: stage_4
  jobs:
  - job: ros_melodic_rostime
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rostime
- stage: stage_5
  jobs:
  - job: ros_melodic_roscpp_traits
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roscpp-traits
- stage: stage_6
  jobs:
  - job: ros_melodic_roscpp_serialization
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roscpp-serialization
- stage: stage_7
  jobs:
  - job: ros_melodic_message_runtime
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-message-runtime
- stage: stage_8
  jobs:
  - job: ros_melodic_rosbuild
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosbuild
  - job: ros_melodic_rosmake
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosmake
  - job: ros_melodic_cmake_modules
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-cmake-modules
  - job: ros_melodic_ros_environment
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-ros-environment
- stage: stage_9
  jobs:
  - job: ros_melodic_rospack
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rospack
- stage: stage_10
  jobs:
  - job: ros_melodic_roslib
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roslib
- stage: stage_11
  jobs:
  - job: ros_melodic_rosunit
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosunit
- stage: stage_12
  jobs:
  - job: ros_melodic_rosconsole
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosconsole
  - job: ros_melodic_std_msgs
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-std-msgs
- stage: stage_13
  jobs:
  - job: ros_melodic_rosgraph_msgs
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-rosgraph-msgs
  - job: ros_melodic_roslang
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roslang
  - job: ros_melodic_xmlrpcpp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-xmlrpcpp
- stage: stage_14
  jobs:
  - job: ros_melodic_roscpp
    steps:
    - script: .scripts/build_linux.sh
      env:
        ANACONDA_TOKEN: $(ANACONDA_TOKEN)
      displayName: Build ros-melodic-roscpp
